language: java
jdk:
  - openjdk8

#Travis CI 를 어느 브랜치가 푸시될때 수행할지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들로 의존상 받으면 해당디렉토리에 캐시, 같은 의존성은 다음 배포때부터 다시안받도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#master 브랜치에 푸시되었을때 수행하는 명령어
script: "./gradlew clean build"

#S3이용
before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #트레비스에 설정된값
    secret_access_key: $AWS_SECRET_KEY #트레비스에 설정된값
    bucket: my-springboot2-build # S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deploy: true

# CI 실행완료시 메일로 알람
notifications:
  email:
    recipients:
      udon1@naver.com

#  권한주는거
before_install:
  chmod +x gradlew
